@extends('layouts.master')

@section('content')

    <div class="container">
        <img width="100%" src="/uploads/images/become_sponsor.jpg" class="img-responsive" alt="Feedback">
        <div class="applying-area" >
            <h3 class="frame-title">
                SPONSORSHIP PACKAGES OVERVIEW
            </h3>
            
            <div class="padl">

                <h4 class="font" >
                    Platinum : $10,000
                </h4>

                <h4 class="font">
                    Gold :  <span>$7,000</span>
                </h4>
                <h4 class="font">
                    Silver:<span>$5,000</span>
                </h4>


                <h4 class="font">
                    Bronze : <span>$3,000</span>
                </h4>
                <h3>
                    SPONSOR BENEFITS
                </h3>
                <ul type="circle" class="sponsors-rules">
                    <li>
                        	Hosting a special session during the Conference plus all the Platinum Package benefits.

                    </li>

                    <li>
                        	Support the ideas of city and regional planning both nationally and globally.

                    </li>

                    <li>
                        	Reward partners, clients and staff with learning and networking.

                    </li>

                    <li>
                        	Media opportunities from publicity generated by the event.

                    </li>

                    <li>
                        	Exposure to an interested, relevant and influential audience before, during and after the event.

                    </li>

                    <li>
                        	Acknowledgement for contributing to the industry.

                    </li>

                    <li>
                       	Recognition of sponsoring organization's efforts in promoting skills and knowledge to other markets through technology, transfer, training and sustainable local industry development.

                    </li>

                    <li>
                        	The opportunity to provide promotional literature and research to target market.

                    </li>


                    <li>
                        	Increased opportunity for extremely targeted brand placement.

                    </li>

                    <li>
                        	Access to all Conference session, which will increase networking opportunities while providing valuable industry education and updates.

                    </li>

                    <li>
                        	The opportunity to increase knowledge of standards, methodologies and their applications.

                    </li>

                    <li>
                        Up to delegates consisting of senior planners and researchers.

                    </li>

                </ul>

                <table border="1" class="sponsor-ship-table">

                    <tr>
                        <td rowspan="2" class="rule font text-center">
                            Sponsor Benefits
                        </td>

                        <th class=" rule text-center">
                            Platinum
                        </th>
                        <th class="rule text-center">
                            Gold
                        </th>
                        <th class="rule text-center">
                            Silver
                        </th>

                        <th class="rule text-center">
                            Bronze
                        </th>
                    </tr>

                    <tr>

                        <td>
                            $10,000
                        </td>
                        <td>
                            $7,000
                        </td>
                        <td>
                            $5,000
                        </td>

                        <td>
                            $3,000
                        </td>
                    </tr>



                    <tr>
                        <td class="text-left">
                            Status of Conference partner over the period of two years.
                        </td>
                        <td>
                            √
                        </td>

                        <td>
                            -
                        </td>

                        <td>
                            -
                        </td>

                        <td>
                            -
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Acknowledged major sponsor in all marketing posts
                        </td>
                        <td>
                            √
                        </td>

                        <td>
                            -
                        </td>

                        <td>
                            -
                        </td>

                        <td>
                            -
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Advertisement in Conference programme
                        </td>
                        <td>
                            Colored page
                        </td>

                        <td>
                            Colored page
                        </td>

                        <td>
                            Colored page
                        </td>

                        <td>
                            Logo
                        </td>
                    </tr>


                    <tr>
                        <td class="text-left">
                            Acknowledged with the company logo in all conference publications
                        </td>
                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Complimentary farewell dinner
                        </td>
                        <td>
                            7 tickets
                        </td>

                        <td>
                            5 tickets
                        </td>

                        <td>
                            3 tickets
                        </td>

                        <td>
                            1 tickets
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Complimentary Conference material and publications

                        </td>
                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Company's website linked to CST website prior to the Conference

                        </td>
                        <td>
                            4 months
                        </td>

                        <td>
                            3 months
                        </td>

                        <td>
                            2 months
                        </td>

                        <td>
                            1 months
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Company's website linked to CST website during to the Conference
                        </td>
                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>
                    </tr>

                    <tr>
                        <td class="text-left">
                            Certificate of Appreciation
                        </td>
                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>

                        <td>
                            √
                        </td>
                    </tr>


                </table>
                <h3>
                    FOR EXHIBITORS
                </h3>
                <ol type="1">
                    <li>
                        Booth: Stand Area (2m x 2m) = $2,000
                        *Full Free Registration for one member
                        *For a bigger space

                    </li>

                    <li>
                        booths (2m x 2m each) may be booked for $3,500 instead of $4,000.
                        *Bookings made for conference in Egypt are to be paid for in dollars ($) while those outside of Egypt are to be paid in Euros.

                    </li>
                </ol>
                <div class="text-right font">

                    <a href="/sponsorship_form/{{$id}}">Accept And Continue <img src="uploads/images/arrow-pointing-to-right.png" class="continue-btn"/></a>
                </div>

            </div>


        </div>

    </div>

@endsection